# Commands to open items

[opener]
edit = [
    { run = '${EDITOR:-vim} -- "$@"',                       desc = "env EDITOR", block = true, for = "unix" },
]
bat_cat = [
    { run = 'bat --paging=always --theme-dark=TwoDark --decorations=never --color=always -- "$@" || less -- "$@"', desc = "Pager (bat|less)", block = true, for = "unix" },
]
open_pdf = [
    { run = 'okular "$@" & disown',                         desc = "Okular", for = "unix" },
]
imv_feh = [
    { run = 'imv -- "$@" || feh -- "$@"',                   desc = "Open Image", block = false, for = "unix" },
]
xdg_open = [
    { run = 'xdg-open "$@" &',                              desc = "xdg open", for = "unix" },
]
reveal = [
    { run = 'xdg-open "$(dirname "$@")"',                   desc = "xdg open dir", block = false, for = "unix" },
]
extract = [
    { run = 'ya pub extract --list "$@"',                   desc = "Extract here", for = "unix" },
]
mpv_vlc = [
    { run = 'mpv --loop --volume=65 "$@" || vlc "$@"',                  desc = "mpv", orphan = true, for = "unix" },
]

# Rules to open items
[open]
rules = [
    # Folder
    { name = "*/", use = [ "edit", "xdg_open", "reveal" ] },
    # Text
    { mime = "text/*", use = [ "bat_cat", "edit", "reveal" ] },
    # Image
    { mime = "image/*", use = [ "imv_feh", "xdg_open", "reveal" ] },
    # Media
    { mime = "{audio,video}/*", use = [ "mpv_vlc", "reveal" ] },
    # PDF
    { mime = "application/{pdf,doc}", use = [ "open_pdf", "reveal" ] },
    # Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
    # Empty file
    { mime = "inode/empty", use = [ "edit", "reveal" ] },
    # Fallback
    { name = "*", use = [ "xdg_open", "reveal" ] },
]

