#!/usr/bin/env bash

### Colors
green="\033[1;32m"
red="\033[1;31m"
mild_green="\033[38;2;10;110;10m"
no_col="\033[0m"

function main() {
    local -i project_index=${1:-0}
    local project_dir="${HOME}/Notes/Programming"
    local project_source_file="${project_dir}/Projects/Project$project_index.c++"
    local requested_editor="$2"

    if [[ $# -eq 0 ]] ; then
        echo -e "Usage: ${mild_green}$(basename $0) <Index> <EDITOR>${no_col}"
        return 1
    fi

    if [[ ! -d "${project_dir}" ]]; then
        echo -e "[${red}ERROR${no_col}]: '${project_dir}' not found"
        return 1
    fi

    if [[ ! -f "${project_source_file}" ]] && [[ $project_index -ne 0 ]]; then
        touch "${project_source_file}" && {
            echo -e "Created ${green}${project_source_file}${no_col}"
            return 0
        }
    fi

    if [[ -n "${requested_editor}" ]] && command -v "${requested_editor}" &> /dev/null; then
        EDITOR="${requested_editor}"
    else
        EDITOR="${EDITOR:-"vim"}"
    fi


    if [[ $project_index -eq 0 ]] ; then
        "${EDITOR}" "${project_dir}/Projects.md"
        return 0
    else
        if [[ $project_index =~ ^([0-9]+)$ ]]; then
            ${EDITOR} "${project_source_file}"
            return 0
        fi
    fi

}

main "$@"
