#!/usr/bin/env bash

# Color definitions
HL="\033[1m"
NC="\033[0m"
MSG_COL="\033[38;2;255;240;200m"
RED="\033[38;2;255;0;0m"

#  Message helpers
function INFO()  { printf "%b\n" "[${HL}*${NC}] ${MSG_COL}$1${NC}"; }
function ERROR() { printf "%b\n" "[${RED}!${NC}] $1"; exit 1; }

# Usage info
function Usage() {
    printf "%b\n" \
        "${HL}Usage${NC}: $(basename "$0") [options] <YouTube-Playlist-URL>" "" \
        "${MSG_COL}Options:${NC}" \
        "  -o <dir>      Set custom output directory" \
        "  -h, --help    Show this help message" "" \
        "${MSG_COL}Example:${NC}" \
        "  $(basename "$0") -o ~/Music 'https://youtube.com/playlist?list=xyz123'" ""
    exit 0
}

function main() {
    # Default configuration
    local concurrent_downloads=4
    local download_directory="$(realpath .)"
    local playlist_url=""

    # Argument parsing
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -o)
                shift
                [[ -z "$1" ]] && ERROR "Missing directory after -o"
                download_directory="$(realpath "$1")"
                ;;
            -h|--help)
                Usage
                ;;
            *)
                playlist_url="$1"
                ;;
        esac
        shift
    done

    # Checks
    [[ -z "$playlist_url" ]] && ERROR "No playlist URL provided."
    [[ ! -d "${download_directory}" ]] && ERROR "Directory '${download_directory}' doesn't exist."
    cd "${download_directory}" || ERROR "Cannot change directory '${download_directory}'"

    # Start Download
    INFO "Downloading into: ${download_directory}"
    INFO "Playlist: ${playlist_url}"

    yt-dlp \
        -f "bestaudio[ext=m4a]/bestaudio[ext=webm]/bestaudio" \
        -N "$concurrent_downloads" \
        --embed-thumbnail --convert-thumbnails jpg \
        --add-metadata \
        --metadata-from-title "%(artist)s - %(title)s" \
        --yes-playlist \
        -o "%(title).150s.%(ext)s" \
        "$playlist_url"
}

main "$@"

