#!/usr/bin/env bash

function LOG() {
    local type_="$1"; shift
    case "${type_}" in
        info)
            printf '[*]: %s' "$*"
            ;;
        warn)
            printf '[!]: %s' "$*"
            ;;
        error)
            printf '[!!!]: %s' "$*"
            ;;
    esac
}

function Exit() {
    printf "\n"
    exit $1
}

function main() {
    local -a args=("$@")
    local -a command_=("")
    local -i time=1 # in seconds

    test $# -ne 0 || LOG error "No command given"

    for arg in "${args[@]}"; do
        if [[ "${arg}" == -* ]]; then
            case "${arg}" in
                -t|-*time)
                    time=${args}
                    ;;
                *)
                    LOG error "Invalid command: '${arg}'"
                    ;;
            esac
        else
            command_=("${arg}")
        fi
    done

    trap 'Exit 0' SIGINT
    trap 'Exit 1' SIGTERM

    while :; do
        tput sc          # Save cursor position
        tput cup 0 0     # Move cursor to the top-left
        "${command_[@]}" # Run the command again
        tput rc          # Restore cursor position
        sleep $time
    done
}

main "$@"

